{{- if .Values.global.rbac.create }}
---
# ServiceAccount for database migration jobs (needs admin access)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flightctl-db-migration
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-db-migration
    security.level: high-privilege

---
# ServiceAccounts for internal namespace services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flightctl-periodic
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    flightctl.service: flightctl-periodic

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flightctl-alert-exporter
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    flightctl.service: flightctl-alert-exporter

---
# Role for accessing admin database secrets (superuser only)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flightctl-db-admin-access
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-db-admin
    security.level: superuser-privilege
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["flightctl-db-admin-secret"]
  verbs: ["get"]

---
# Role for accessing migration database secrets (schema changes only)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flightctl-db-migration-access
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-db-migration
    security.level: schema-privilege
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["flightctl-db-migration-secret"]
  verbs: ["get"]

---
# RoleBinding for migration jobs to access both admin and migration secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flightctl-db-migration-admin-access
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-db-migration
    security.level: superuser-privilege
subjects:
- kind: ServiceAccount
  name: flightctl-db-migration
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
roleRef:
  kind: Role
  name: flightctl-db-admin-access
  apiGroup: rbac.authorization.k8s.io

---
# RoleBinding for migration jobs to access migration secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flightctl-db-migration-schema-access
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-db-migration
    security.level: schema-privilege
subjects:
- kind: ServiceAccount
  name: flightctl-db-migration
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
roleRef:
  kind: Role
  name: flightctl-db-migration-access
  apiGroup: rbac.authorization.k8s.io

---
# Role for checking migration job status (used by init containers)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flightctl-job-status-reader
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-job-status
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]

---
# Role for accessing application database secrets in internal namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flightctl-db-app-access
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-db-app
    security.level: application
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["flightctl-db-app-secret"]
  verbs: ["get"]

---
# RoleBinding for all services to read job status (supports both same and cross-namespace)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flightctl-job-status-reader
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-job-status
subjects:
- kind: ServiceAccount
  name: flightctl-worker
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
- kind: ServiceAccount
  name: flightctl-periodic
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
- kind: ServiceAccount
  name: flightctl-alert-exporter
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
- kind: ServiceAccount
  name: flightctl-api
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: flightctl-alertmanager-proxy
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: flightctl-job-status-reader
  apiGroup: rbac.authorization.k8s.io

---
# RoleBinding for all services to access app secrets (supports both same and cross-namespace)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flightctl-db-app-access
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
  labels:
    app: flightctl-db-app
    security.level: application
subjects:
- kind: ServiceAccount
  name: flightctl-worker
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
- kind: ServiceAccount
  name: flightctl-periodic
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
- kind: ServiceAccount
  name: flightctl-alert-exporter
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
- kind: ServiceAccount
  name: flightctl-api
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: flightctl-alertmanager-proxy
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: flightctl-db-app-access
  apiGroup: rbac.authorization.k8s.io

{{- end }}
